product:
  yml: Product Profile Dev

spring:
  data:
    mongodb:
      database: ProductDB
      uri: 'mongodb+srv://${BD_USER}:${BD_PASSWORD}@cluster0.m5vgmwl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'